### ISSUE TITLE
Support invoice adjustments

### ISSUE THREAD

**Issue by mfb** [bitpay/php-bitpay-client#137]
This library should support invoice adjustments (for accepting overpayments and underpayments) but looks like this hasn't been implemented yet?

**Comment by ionux** [comment]
Thanks for your feedback, @mfb.  We've got this on our roadmap for upcoming versions of the library!

**Comment by mfb** [comment]
Great, thanks! Is there a pubilc roadmap online somewhere?

**Comment by ionux** [comment]
No, sorry @mfb.  Some of our planning for future products is super top secret and, therefore, black vans would show up outside my house if I shared them. ;)

Seriously though, we'd like to do a lot of improvements - this possibly being one but we are limited on resources at the moment.  It's on the to do list, however!

**Comment by dave7280** [comment]
6 months later and nothing has been done.
