### ISSUE TITLE
item.php Regular expression validation is malfunctioning and it should be changed 

### ISSUE THREAD

**Issue by madhank** [bitpay/php-bitpay-client#141]
Should the regular expression be avoided and we use the standard checking using php. The regular expression was giving errors for price=0.10 (claiming price must be formatted as a float) and after my modification it worked. Can you please check on this and get a fix.
/**
     * @param float $price
     *
     * @return ItemInterface
     */
    public function setPrice($price)
    {
        /*if (1 !== preg_match('/^[0-9]+(?:\.[0-9]{1,2})?$/', $price)) {
            throw new \Bitpay\Client\ArgumentException("Price must be formatted as a float");
        }*/

        if(!is_numeric($price)){ //check if price is number
             throw new \Bitpay\Client\ArgumentException("Price is not a valid number");
        }

        if(!is_float($price)){ //check if price is float
            throw new \Bitpay\Client\ArgumentException("Price must be formatted as a float");
        }

        if(floatval($price) < 0.000006){
             throw new \Bitpay\Client\ArgumentException("Price must be minmum 0.00006 BTC");
        }

        $this->price = $price;

        return $this;
    }

**Comment by ionux** [comment]
@madhank thanks for bringing this to our attention.  You're right that this code snippet is unnecessarily complicated and should use the built-in functions instead.  This would be more clear and therefore easier to maintain.  I'm working on a set of updates for the library now and should be updated this week.

**Comment by madhank** [comment]
@ionux , there is another issues where the regular expression used in BCEngine input function is malfunctioning too. Has anyone flagged? Coz it seems that it does not run in a nginx environment and always complains "The input must be a numeric string in decimal or hexadecimal (with leading 0x) format". Shall i flag that as a bug?

**Comment by ionux** [comment]
Nobody has flagged it yet, afaik.  Definitely open an issue for anything you find that's a bug and we will investigate!

**Comment by ionux** [comment]
@madhank I also wanted to point out we have a new forum called BitPay Labs where you can post threads, ask questions, talk to the developers about a project, etc...  That will be a great resource for you to connect with us, as well:  http://bitpaylabs.com/

**Comment by madhank** [comment]
Thank you ionux. Will connect there and my company will love to closely stay in touch with you as we have decided to chose you as our official payment provider :-)
