### ISSUE TITLE
Could not decode key

### ISSUE THREAD

**Issue by sprain** [bitpay/php-bitpay-client#142]
When running the pairing code, I keep getting the following error as soon as `$client = $bitpay->get('client');` is called, no matter what I try:

```
Fatal error: Uncaught exception 'Exception' with message
'Could not decode key' in src/Bitpay/Storage/EncryptedFilesystemStorage.php on line 76

Call Stack:
    0.0002     227984   1. {main}() /my/local/path/bitpay/pairing.php:0
    0.0569    2601336   2. Bitpay\Bitpay->get() /my/local/path/bitpay/pairing.php:24
    0.0569    2601600   3. Symfony\Component\DependencyInjection\ContainerBuilder->get() /my/local/path/bitpay/php-client/src/Bitpay/Bitpay.php:132

```

	<?php
    //pairing.php
	
	require __DIR__.'/php-client/vendor/autoload.php';

	$storageEngine = new \Bitpay\Storage\EncryptedFilesystemStorage('mySecretPassword');
	$privateKey    = $storageEngine->load('bitpay.pri');
	$publicKey     = $storageEngine->load('bitpay.pub');

	$bitpay = new \Bitpay\Bitpay(
		array(
			'bitpay' => array(
				'network'     => 'livenet',
				'public_key'  => 'bitpay.pub',
				'private_key' => 'bitpay.pri',
			)
		)
	);

	$client = $bitpay->get('client');

Simply persisting and loading the keys by `EncryptedFilesystemStorage` works fine.

**Comment by ionux** [comment]
Try just FilesystemStorage and see if that will work for the time being and be sure to store your keys in a non-web accessible location.  Couple things to check:  is the location you are trying to store the keys writable? Are you using the library in a vm or environment that is changing or moved from one server to another?  The encrypted storage uses a fingerprint based on several server environment parameters.

**Comment by ionux** [comment]
@sprain Any update on your issue since I mentioned some things to try last week?

**Comment by sprain** [comment]
@ionux I did not have the time to try. Your reply is still waiting in my inbox. Will report back here once I get to it.

**Comment by ionux** [comment]
@sprain Ok, no problem!  Just wanted to check in and make sure your issue was being addressed. :)

**Comment by Watch-Video** [comment]
The issue password decoding from this call 
new \Bitpay\Storage\EncryptedFilesystemStorage('dN$8WNaT}j<gD3*q'); 
This is a very strong password but cannot be fully maintained if i change it to another with no special chars it works

**Comment by ionux** [comment]
Thanks, I'll look into it.
