### ISSUE TITLE
Error when creating payout: This endpoint does not support the `pos` facade

### ISSUE THREAD

**Issue by 4ley** [bitpay/php-bitpay-client#145]
I tried the example found [here][1] which unfortunately result in an error using testnet.

    {"error":"This endpoint does not support the `pos` facade"}

The request looks as follows

    POST https://test.bitpay.com:443/payouts HTTP/1.1
    ...
    {"token":"__REPLACED__","amount":10,"currency":"USD","instructions":[{"label":"Test","address":"__REPLACED__","amount":10}],"effectiveDate":"2015-05-29T14:05:38.000Z","pricingMethod":"bitcoinbestbuy","guid":"__REPLACED__","nonce":__REPLACED__,"reference":"123","notificationURL":"__REPLACED__"}

*Note: REPLACED was placed by me to not disclose private information.*

  [1]: https://github.com/bitpay/php-bitpay-client/blob/master/examples/CreatePayout.php

**Comment by ionux** [comment]
@4ley the payouts endpoint requires the payroll facade.

**Comment by 4ley** [comment]
As I understood, I have to set it on the token class. Thats what I did. Here is my code:

    $instruction = new \Bitpay\PayoutInstruction();
    $instruction
        ->setAmount(10)
        ->setAddress('__REPLACED__')
        ->setLabel('Test');

    $time = gmdate("Y-m-d\TH:i:s\.", time()+3000)."000Z";

    $token = new \Bitpay\Token();
    $token
        ->setFacade('payroll')
        ->setToken('__REPLACED__');

    $payout = new \Bitpay\Payout();
    $payout
        ->setEffectiveDate($time)
        ->setCurrency(new \Bitpay\Currency('USD'))
        ->setPricingMethod('bitcoinbestbuy')
        ->setReference('__REPLACED__')
        ->setNotificationUrl('__REPLACED__')
        ->setToken($token)
        ->addInstruction($instruction);

**Comment by ionux** [comment]
Ok, gotcha.  It sounds like your account was paired with a POS token originally.  That's the least-privileged access token (and the default one created).  However, if you make a call to `getTokens()` it should respond with all of the access tokens associated with your account.  If you do have a payroll token, use that one, otherwise the default POS token will be returned and used.  Here's the example code for that call: https://github.com/bitpay/php-bitpay-client/blob/master/examples/GetTokens.php

**Comment by 4ley** [comment]
Hm, very strange the `$client->getTokens()` returns NULL

**Comment by sambohler** [comment]
@4ley , have you created any tokens?  You might want to follow our [tutorials](https://github.com/bitpay/php-bitpay-client/tree/master/examples/tutorial).

In 001.php, keys are generated and stored.
In 002.php, a (POS) token is created.  You'll want to modify [the create token](https://github.com/bitpay/php-bitpay-client/blob/master/examples/tutorial/002.php#L67) snippet to the following to create a payroll token:

```php
$token = $client->createToken(
    array(
        'facade' => 'payroll',
        'label' => 'You can insert a label here',
        'id' => (string) $sin,
    )
); 
```

That'll create a payroll token, but you'll still need to pair it with your account.  At the bottom of the same file, after `$persistThisValue = $token->getToken();` add `$pairingCode = $token->getPairingCode();`

And then print out $pairingCode however you like.  Log in to your BitPay account and then go to Access Tokens and paste the pairing code and click Find.  If everything worked, your account will now be associated with that payroll facade token.

**Comment by 4ley** [comment]
Your code gives me the following error:

`PHP Fatal error:  Uncaught exception 'Bitpay\Client\ArgumentException' with message 'pairing code is not legal' in /home/www/includes/bitpay/vendor/bitpay/php-client/src/Bitpay/Client/Client.php:474`

**Comment by sambohler** [comment]
What version of the PHP-Bitpay-Client are you using?

**Comment by 4ley** [comment]
The VERSION file says 2.0.0

**Comment by sambohler** [comment]
To use non-POS facade tokens, you'll need to be using the unreleased master branch.
To do this, in your composer json, the require for our client should like like the following:
```json
...
"require": {
    ...
    "bitpay/php-client": "dev-master"
    ...
},
...
```
where the `...` are other possible code snippets

**Comment by 4ley** [comment]
Okay I made the update, now it gives me

`PHP Fatal error:  Uncaught exception 'Bitpay\Client\BitpayException' with message '500: Facade not allowed' in /home/www/master/includes/bitpay/vendor/bitpay/php-client/src/Bitpay/Client/Client.php:502`

**Comment by sambohler** [comment]
I just checked, and you're right, the payroll facade isn't listed.  It requires manual approval to get a token for that facade, so you'll need to contact support@bitpay.com with a request for approval.

**Comment by 4ley** [comment]
Thanks. I've sent a request.
