### ISSUE TITLE
Invoice class has no set/getToken methods

### ISSUE THREAD

**Issue by 4ley** [bitpay/php-bitpay-client#148]
To issue invoice refunds, I need to get the invoice resource token, but there are no methods for it.
And also please check the following lines on [Client::getInvoice](https://github.com/bitpay/php-bitpay-client/blob/master/src/Bitpay/Client/Client.php#L568) setToken is commented. Why?

**Comment by sambohler** [comment]
We had previously fixed this in a PR that was meant to add refund functionality that never got merged: https://github.com/abishekrsrikaanth/php-bitpay-client/commit/2a981e707a09fe406abd1a07ed87379451e0d60a

I'll look into it, thank you!
