### ISSUE TITLE
Cannot update to version 2.2.4

### ISSUE THREAD

**Issue by 4ley** [bitpay/php-bitpay-client#149]
As the new version 2.2.4 was published some hours ago I try to fetch it with `php composer.phar update` but its not showing any new updates. Thats how my `composer.json` looks like:

    {
        "require": {
            "bitpay/php-client": "dev-master"
        }
    }

**Comment by sambohler** [comment]
Packagist hasn't updated yet based upon the new version.  It takes some time.  Once it does, it will become available through composer.
