### ISSUE TITLE
Multiple Items on Invoice

### ISSUE THREAD

**Issue by k-sorrels** [bitpay/php-bitpay-client#151]
I've read through the documentation and have been unable to find how to use an Invoice with multiple items. I'm not sure if it's API support or just the library. 

I understand that Bills will allow multiple items, but it appears the Invoices will not. While using a bill seems like a good idea, there is no notification for the payment of the bill.

Assuming the item count of the invoice must be one:
How can I mock the behavior of an invoice with a bill ( including notifications and point of sale data)?
Can we attach a bill to an Invoice?

**Comment by ionux** [comment]
Think of a BitPay invoice in terms of payment for a single order.  Orders themselves (based on your shopping cart implementation) can contain multiple items.

There isn't a notification for payment of a bill, however you can query the status of the bill periodically.

Bills are invoices that you can pay at a later date.  Invoices are for paying for an order right now and will expire within 15 minutes.

**Comment by 4ley** [comment]
If you'd like to programmatically create bills, you will find the Rich [Morgans snippet @labs.bitpay.com](https://labs.bitpay.com/t/php-bitpay-client-how-to-create-a-bill/469/2) useful. You will have to modify Client.php and add the following code to the Client class.

    public function createBill(\Bitpay\Bill $bill)
    {
        $request = $this->createNewRequest();

        $request->setMethod(Request::METHOD_POST);
        $request->setPath('bills');

        $body = array(
            'items' => array(array('description' => 'somecooldescription', 'price' => 1.45, 'quantity' => 5)),
            'guid'  => Util::guid(),
            'nonce' => Util::nonce(),
            'token' => '7U24AhTLM3A36iN4bUsEvcEcxB8UeEPSn7ghEYuCbkoc',
        );

        $request->setBody(json_encode($body));

        $this->addIdentityHeader($request);
        $this->addSignatureHeader($request);

        $this->request  = $request;
        $this->response = $this->sendRequest($request);

        $response = json_decode($this->response->getBody(), true);

        return array('request' => json_encode($body), 'response' => $this->response->getBody());
    }

You call it like this

    <?php
    require __DIR__ . '/../vendor/autoload.php';

    $bitpay = new \Bitpay\Bitpay(
        array(
              'bitpay' => array(
              'network'     => 'testnet',
              'public_key'  => '/tmp/public.key',
              'private_key' => '/tmp/private.key',
              'key_storage' => 'Bitpay\Storage\FilesystemStorage',
               )
            )
        );

    $client = $bitpay->get('client');
    $tokens = $client->getTokens();

    $client->setAdapter(new \Bitpay\Client\Adapter\CurlAdapter());

    $bill = new \Bitpay\Bill;
    $info = $client->createBill($bill);

    print_r($info);

**Comment by k-sorrels** [comment]
So as far as multiple Invoice Items, Is that a library limitation or is that an API limitation? Do you intend for a single invoice item for the entire shopping cart or can it be more of a pass-through and reflect the original items in the shopping cart?

As far as the bill, I'm actually already in the process of modifying it =) .

**Comment by ionux** [comment]
Check out the API documentation for invoices here: https://bitpay.com/api#resource-Invoices

There's a pass-through field named posData you can use on invoices.

**Comment by k-sorrels** [comment]
Ok, That makes more sense. Thanks.
