### ISSUE TITLE
Unable to convert variable to GMP when initializing Bitpay client class

### ISSUE THREAD

**Issue by ollierexx** [bitpay/php-bitpay-client#155]
I have generated my private, public and sin keys according to the documentation, and added their respective paths to my yaml config file.
I can load the main bitpay class fine, however I cannot initialize the client class, as I receive the following error:
PHP warning:  gmp_cmp(): Unable to convert variable to GMP - string is not an integer in /home/vagrant/laravel/vendor/bitpay/php-client/src/Bitpay/Math/GmpEngine.php on line 26

Any ideas?

**Comment by ionux** [comment]
Hmm, that's the compare function but it's just a warning.  Can you copy/paste the complete stack trace for the error you're experiencing?

**Comment by ollierexx** [comment]
Here is the stack trace:
http://pastebin.com/qcUXtKDE

It seems there is a problem with the private key, so I tried to regenerate it again, using the following code:
        $manager = new \Bitpay\KeyManager(new \Bitpay\Storage\FilesystemStorage());
        $path1 = base_path() . "/bitpay_keys/private";
        $priv = new \Bitpay\PrivateKey($path1);
        $priv->generate();
        $manager->persist($priv);
        $path2 = base_path() . "/bitpay_keys/public";
        $pub = new \Bitpay\PublicKey($path2);
        $pub->setPrivateKey($priv);
        $pub->generate();
        $manager->persist($pub);
        $path3 = base_path() . "/bitpay_keys/sin";
        $sin = new \Bitpay\SinKey($path3);
        $sin->setPublicKey($pub);
        $sin->generate();
        $manager->persist($sin);

However I still get the same problem.
Thanks

**Comment by ollierexx** [comment]
Looking at the error again it may be because I am not using encrypted keys, how can I change my yml config to use non-encrypted storage?

**Comment by ollierexx** [comment]
I have solved the problem by using encrypted storage, however it would be beneficial to add to the documentation on select storage types.
