### ISSUE TITLE
Invoice exception state

### ISSUE THREAD

**Issue by jonhkr** [bitpay/php-bitpay-client#157]
In the docs (https://bitpay.com/docs/invoice-states), we have the information that `exceptionState` can be any of:
- `false`: 
The invoice is not in an exception state.
- `paidPartial`: 
If the amount paid is less than the amount expected then the invoice is marked as being partially paid.
- `paidOver`: 
If the amount paid is greater than the amount expected then the invoice is marked as being overpaid.
- `paidLate`: 
The invoice was paid outside the 15-minute payment window.

But in the invoice class we have this: https://github.com/bitpay/php-bitpay-client/blob/master/src/Bitpay/Invoice.php#L647

**Comment by ionux** [comment]
Yep, you are correct.  This looks like this is the only place in the library referenced as a boolean.  If you'd like to submit a PR, we'll be happy to test it out with our API 2 plugins!

**Comment by jonhkr** [comment]
I've opened a PR. May you please merge it and create a release? I need this to finish my integration with Bitpay.
