### ISSUE TITLE
Difficulty running in Drupal

### ISSUE THREAD

**Issue by DMalone87** [bitpay/php-bitpay-client#159]
I'm working to incorporate this library into a Drupal project and having some trouble... For whatever reason I can't seem to load classes when I need to. For example, when I create a new bitpay object I get this error:

>Fatal error: Class 'Symfony\Component\DependencyInjection\ContainerBuilder' not found in [...]\Bitpay\Bitpay.php on line 65

Anyone have advice on this? For reference, I'm using the [Libraries API](https://www.drupal.org/project/libraries) to load the library.

**Comment by aleitner** [comment]
@DMalone87 It sounds like Symfony may not have been installed correctly. How are you obtaining the library, and how exactly in your code are you requiring the BitPay Library? 

If you are cloning the source code from github, it is necessary for you to run a `composer install` in the source code folder.

To use the library you need to use our Autoloader code as such:
```php
$autoloader = __DIR__ . '/relative/path/to/Bitpay/Autoloader.php';
if (true === file_exists($autoloader) &&
    true === is_readable($autoloader))
{
    require_once $autoloader;
    \Bitpay\Autoloader::register();
} else {
    throw new Exception('BitPay Library could not be loaded');
}
```

Also, let me know what version of PHP you are using. We only support PHP 5.4+

Please let me know if this helps.

**Comment by DMalone87** [comment]
Yes, I was using the auto loader code by way of Libraries, but it wasn't working. I removed the libraries dependency and just loaded the library into the module itself and that seems to work.
