### ISSUE TITLE
Inconsistent escaping of strings

### ISSUE THREAD

**Issue by braydonf** [bitpay/php-bitpay-client#166]
Some of the fields of the data that is signed includes escaped slashes, others do not, however it's not necessary, and may lead to issues with generating a hash differently:

```
'{"notificationURL":"https:\/\/store.example.com\/bitpay\/callback"}'
```

```bash
~$ node
> var a = JSON.parse('{"notificationURL":"https:\/\/store.example.com\/bitpay\/callback"}');
> JSON.stringify(a)
'{"notificationURL":"https://store.example.com/bitpay/callback"}'
```

**Edit:** This may be a `print_r` issue.

**Comment by ionux** [comment]
Use the `JSON_UNESCAPED_SLASHES` option when encoding, if this is an issue.  The behavior technically correct, however.  Strings used inside a `<script>` tag cannot contain unescaped forward slashes like `</`.  Also, if the a specific value signed correctly has slashes escaped but Node removes those for some (I'm sure) interesting reason, then it is a different value which will produce a different hash, yes.

See: http://php.net/manual/en/function.json-encode.php

**Comment by braydonf** [comment]
Thanks for the info. 

It looks like Node.js will automatically convert `https:\/\/store.example.com\/bitpay\/callback` into `https://store.example.com/bitpay/callback` if it's a string assigned to a variable, the same way that JSON.parse/stringify is behaving. Had the same issue with utf-8 characters `\u00e8` being automatically converted to `è`, and was able to retain the format that was originally hashed by using `\\u00e8`.
