### ISSUE TITLE
Dependencies in composer.json not compatible with Symfony 3.0

### ISSUE THREAD

**Issue by iquito** [bitpay/php-bitpay-client#169]
Because of the specific dependencies on symfony/config in version 2.5.x and symfony/dependency-injection in version 2.5.x the library cannot be installed/used with Symfony 3.

Maybe the library still works with Symfony 3, if no deprecated features are being used, so in the best case scenario only the version constraints would need to be changed.

**Comment by kleetus** [comment]
I was reviewing the Symfony changelog for the 3.0 release last month. There are a few hints in there that some previously deprecated (in < 3.0) features were removed. This might be one source of some trouble. I also reviewed the listed security fixes. I don't think any of those fixes affect this library, but I will keep my eyes peeled for this. Apart from critical security flaws in symfony* 2.5, is there a good reason to update Symfony 3?

**Comment by iquito** [comment]
I do not know your internals on how you use symfony/config and symfony/dependency-injection, but I doubt there are that many changes in these components which affect your library, or which would mean a lot of changes. Symfony 3.0 is basically Symfony 2.8 without backwards compatability layer, and Symfony makes it easy to detect deprecated usages.

You do not need to update to Symfony 3 - you just need to support it, by allowing symfony/config and symfony/dependency-injection to be used in the 3.0.x versions aswell as in the 2.5 versions. Otherwise you lock out everybody using Symfony 3.0. The new Symfony version was just released, so I guess I am the first one to request it, but you will need to be compatible at some point anyway, because all new projects will probably start using Symfony 3.0 soon.

**Comment by iquito** [comment]
By the way, I also noticed that you changed the version restrictions from v2.2.3 to v2.2.4 from

    symfony/config: ~2.3
    symfony/dependency-injection: ~2.3

to

    symfony/config: 2.5.*
    symfony/dependency-injection: 2.5.*

Which is a really bad idea - you restrict the usage of these newer library versions to ONLY Symfony 2.5, which is not supported anymore (ended in July 2015), so nobody will be using that specific Symfony version, and therefore nobody can upgrade to newer versions of your library. With ~2.3 at least you supported versions >=2.3 <3.0 .

So my basic suggestion would be for you to test the library with Symfony 3.0 and if it works, then change the version restrictions to

    symfony/config: ^2.3 || ^3.0
    symfony/dependency-injection: ^2.3 || ^3.0

This would enable usage of your library for the Symfony versions 2.3-2.8 and 3.x .

**Comment by gjuric** [comment]
I am running Symfony 2.7.7 and I am stuck on v2.2.3 of this library as well. Can you at least change the dependency to "~2.5" and do another release?

**Comment by kleetus** [comment]
I am looking into this issue. I put a small bit of time before Christmas to see how much work this would be and decided I should engage others on the team about it. I do think it needs to be done, if possible.

**Comment by gjuric** [comment]
I don't think this is a big change, just update the composer file and run the tests. Would a pull request help?

**Comment by kleetus** [comment]
i have one in already #176
