### ISSUE TITLE
[NOTE HHVM: how to fix] Unable to parse file services.xml (XmlFileLoader InvalidArgumentException)

### ISSUE THREAD

**Issue by Invision70** [bitpay/php-bitpay-client#171]
### Error

> Symfony\Component\DependencyInjection\Exception\InvalidArgumentException [ 0 ]: Unable to parse file "vendor/bitpay/php-client/src/Bitpay/DependencyInjection/services.xml".
in "/vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php [ 220 ]"

## How to fix

edit:
`/etc/hhvm/php.ini`

append:
`hhvm.libxml.ext_entity_whitelist = file,http`

**Comment by kleetus** [comment]
I will reopen this issue when I get a customer who runs HHVM
