### ISSUE TITLE
Invoice paymentUrls not supported by PHP client

### ISSUE THREAD

**Issue by leonar15** [bitpay/php-bitpay-client#173]
Hi,
I'm having an issue in that the PHP client simply drops the paymentUrls param when retrieving data from the bitpay server. I've made a pull request that adds support for this feature, but the automated tests are failing and I'm not sure where to fix things.

**Comment by kleetus** [comment]
I think you got the tests passing. I will check into merging this as soon as I can.

thanks

**Comment by leonar15** [comment]
Thanks @kleetus, I was just posting a note about the tests passing.
