### ISSUE TITLE
Client not checking if token is set. No exception thrown.

### ISSUE THREAD

**Issue by dopesong** [bitpay/php-bitpay-client#179]
You get error like this:

>Fatal error: Call to a member function getFacade() on null in payments/vendor/bitpay/php-client/src/Bitpay/Client/Client.php on line 599

Code example:

```php
/** @var \Bitpay\Client\Client $client */
$client = $this->bitpayClient->get('client');
$invoice = $client->getInvoice($invoiceId);
```

**Comment by kleetus** [comment]
I think this is a pretty legit concern quite frankly.

**Comment by kleetus** [comment]
I take back what I said before, the creator of the $client ought to explicitly set the token before calling other methods that require a token:

https://github.com/bitpay/php-bitpay-client/blob/master/tests/Bitpay/Client/ClientTest.php#L26

**Comment by dopesong** [comment]
You show me test how it should be? For real?

https://github.com/bitpay/php-bitpay-client/blob/master/src/Bitpay/Client/Client.php#L560

Your lib not even checking if token was set - and it should.
