### ISSUE TITLE
Incorrect validation of decimal precision 

### ISSUE THREAD

**Issue by mindaugas-dt** [bitpay/php-bitpay-client#185]
Since the variable $price is always a float type, there is a bug when validating the price which is greater than 999 and do not have any decimal places.

E.g. if the price is 1000, do not have any decimal places  and currency is GBP,  strpos($price, '.') becomes false and $decimalPrecision becomes =3, therefore exception is thrown.

[Client.php#L742](https://github.com/bitpay/php-bitpay-client/blob/master/src/Bitpay/Client/Client.php#L742)

**Comment by kleetus** [comment]
thanks for pointing this out. I will repair ASAP
