### ISSUE TITLE
Support for accepting invoice adjustments

### ISSUE THREAD

**Issue by dave7280** [bitpay/php-bitpay-client#186]
This has been posted over one year ago (January 2015) and was said to be implemented:

"This library should support invoice adjustments (for accepting overpayments and underpayments) but looks like this hasn't been implemented yet?"

Any updates on that, or shall we just do it by manual parsing bitpay dashboard?

**Comment by kleetus** [comment]
Over and underpayment business logic should be configured in the dashboard. This library should just deal with the following statuses sent by the BitPay api:

paid
confirmed
complete

Are you expecting this library to do something more specialized?

**Comment by kleetus** [comment]
Circling back on this, if under/over payment behavior is setup properly in the dashboard, then the existing behavior in this library will "just work", Example, you can set under/over payment by percentage or flat amount for all invoices delivered in the dashboard. If this is done, then the api will send a webhook with the proper status.
