### ISSUE TITLE
GetTokens.php example not working

### ISSUE THREAD

**Issue by vercotux** [bitpay/php-bitpay-client#188]
When I try to execute it I receive the following exception:

```bash
Exception 'Exception' with message 'The private key must be in hex format.'

in .../vendor/bitpay/php-client/src/Bitpay/PrivateKey.php:116
```

This is after generating and persisting the public and private keys.

**Comment by vercotux** [comment]
It appears that we need to manually call 

```php
$client->setPrivateKey($privateKey);
$client->setPublicKey($publicKey);
```

These two calls are missing from the example. It appears that Client does not automatically load them from \Bitpay\Bitpay.

**Comment by jdavidlists** [comment]
Yes, at some point the library stopped initializing the Client properly.

This definitely worked in 2.2.7.  It definitely does not work in 2.2.10 and later.  Other problems with 2.2.8 and 2.2.9 prevented us from determining if they had this problem as well.

**Comment by ienev** [comment]
I've upgraded from 2.2.6 to 2.2.12 and my application experiences the same problem. 
@vercotux  I was not able to fix it with manually setting the keys. Can you please post the code that worked for you?

**Comment by kleetus** [comment]
refer to the tutorials for proper usage, the examples are out of date.
