### ISSUE TITLE
CreatePayout.php example: Invalid pricing method?

### ISSUE THREAD

**Issue by vercotux** [bitpay/php-bitpay-client#190]
In [CreatePayout.php](https://github.com/bitpay/php-bitpay-client/blob/be67c286de01924b88490139797632b83681b6e5/examples/CreatePayout.php#L40) the pricing method used is '```bitcoinbestbuy```'.
[BitPay API documentation](https://bitpay.com/api#resource-Payouts) on the other hand says this about the *pricingMethod* parameter:

> **pricingMethod** **string**
>
> Can be \`manual_2\` or \`vwap_24hr\`

Has this changed and left the examples outdated?

**Comment by kleetus** [comment]
the examples are outdated, but I will update

**Comment by kleetus** [comment]
Are you using the payouts api? If so, I want to make sure this is fixed ASAP.

**Comment by vercotux** [comment]
Yes I am using the Payouts API.
