### ISSUE TITLE
2.2.8 (et seq) break backwards compatibility

### ISSUE THREAD

**Issue by jdavidlists** [bitpay/php-bitpay-client#191]
Starting with 2.2.8 (the changelog for which reads in its entirety "Repaired tests based on current changes to the code." despite *significant* differences between git branches 

Switching from 2.2.7 to 2.2.8 or 2.2.9 yields this error:

OpenSSL error(s) are: "error:0607A082:digital envelope
routines:EVP_CIPHER_CTX_set_key_length:invalid key length
error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt

Switching from 2.2.7 to 2.2.10 or any later version yields this error:

Exception "The private key must be in hex format."
At .../php-client/src/Bitpay/PrivateKey.php

Switching back to 2.2.7 makes the errors go away and existing code works again.

Since the project claims to use semantic versioning, 2.2.x releases should be backwards compatible, thus this would appear to be a bug.

Thanks!

**Comment by ienev** [comment]
Some even consider that backward-incompatible changes should only be introduced in major versions. In this case 3.x.x. Although probably one could argue that this specific change doesn't really break backward compatibility.
