### ISSUE TITLE
'orderId' should be optional in \Bitpay\Client getInvoice()

### ISSUE THREAD

**Issue by vercotux** [bitpay/php-bitpay-client#192]
When calling `getInvoice()` in \Bitpay\Client it is assumed that *orderId* is [mandatory](https://github.com/bitpay/php-bitpay-client/blob/cf0ae957cb55cac21396d02386714b09604cbdc5/src/Bitpay/Client/Client.php#L628). I am currently dealing with an issue where BitPay does not return this parameter so Client throws an exception at that line. It should be optional like *paymentUrls*.

**Comment by kleetus** [comment]
We are sending the orderId back from the api, here is an example json decoded response from getInvoice()

array(2) {
  ["facade"]=>
  string(14) "public/invoice"
  ["data"]=>
  array(22) {
    ["url"]=>
    string(61) "https://test.bitpay.com:443/invoice?id="
    ["posData"]=>
    string(0) ""
    ["status"]=>
    string(3) "new"
    ["btcPrice"]=>
    string(8) "0.004742"
    ["btcDue"]=>
    string(8) "0.004742"
    ["price"]=>
    float(1.99)
    ["currency"]=>
    string(3) "USD"
    ["exRates"]=>
    array(1) {
      ["USD"]=>
      float(419.63)
    }
    ["itemDesc"]=>
    string(27) "General Description of Item"
    ["orderId"]=>
    string(10) "0123456789"
    ["invoiceTime"]=>
    int(1459799750853)
    ["expirationTime"]=>
    int(1459800650853)
    ["currentTime"]=>
    int(1459799692372)
    ["guid"]=>
    string(36) "4"
    ["id"]=>
    string(22) "dfsdf"
    ["btcPaid"]=>
    string(8) "0.000000"
    ["rate"]=>
    float(419.63)
    ["exceptionStatus"]=>
    bool(false)
    ["redirectURL"]=>
    string(0) ""
    ["paymentUrls"]=>
    array(4) {
      ["BIP21"]=>
      string(58) "bitcoin:mt1SxLtaczMGpybzMUxe18qw6mxdfds?amount=0.004742"
      ["BIP72"]=>
      string(113) "bitcoin:mt1SxLtaczMGpybzMUxe18qw6mx4vQwfdsfas?amount=0.004742&r=https://test.bitpay.com:443/i/dsfdsafdfasfds"
      ["BIP72b"]=>
      string(63) "bitcoin:?r=https://test.bitpay.com:443/i/dsfadsf"
      ["BIP73"]=>
      string(52) "https://test.bitpay.com:443/i/adfasdfdsafds"
    }
    ["bitcoinAddress"]=>
    string(34) "dafdsfafd"
    ["token"]=>
    string(66) "8FG1PpqrooYJHWDV3jEftC4HadafdasfdadsfdTadsad"
  }
}
