### ISSUE TITLE
PHP7 issues

### ISSUE THREAD

**Issue by insanesvk** [bitpay/php-bitpay-client#193]
Hey,

I'm trying to implement Bitpay, although I ran into several issues with the current version, as it doesn't seem to support PHP7. Here's the travis link for the build under PHP7:
https://travis-ci.org/insanesvk/php-bitpay-client/jobs/115652966

**Comment by kleetus** [comment]
thanks for the report. Would you happen why something in build.sh seg faulted? Did you run things locally?

**Comment by kleetus** [comment]
I am told that one of our sales engineers has a merge request for this ready to submit

**Comment by kleetus** [comment]
are you getting any specific problems using php7 beyond the segfault in the test suite?

**Comment by kleetus** [comment]
After further review, I don't have a urgent need to add support for PHP7

**Comment by Lagg** [comment]
@kleetus If you do anything with people's money, using what the rest of the world that cares about security is using is a pretty urgent need. I'm sick of telling you guys that deal in bitcoin this. Fix your shit.
