### ISSUE TITLE
date_default_timezone_set sideffects

### ISSUE THREAD

**Issue by kerneldemon** [bitpay/php-bitpay-client#196]
Some of the library declarations contain the following line of code at the top:

```php
date_default_timezone_set('UTC');
```

This creates undesirable side effects for servers that use non-UTC timezones whenever any library class is autoloaded. This also violates PSR-1:
```
2.3. Side Effects

A file SHOULD declare new symbols (classes, functions, constants, etc.) and cause no other side effects, or it SHOULD execute logic with side effects, but SHOULD NOT do both.
```

**Comment by dopesong** [comment]
@kleetus any response on this?

**Comment by kleetus** [comment]
agreed for the most part.

**Comment by dopesong** [comment]
disagree with what?

**Comment by kleetus** [comment]
> disagree with what?

Assuming you are referring to my comment "for the most part", I did not have full context over what exact code @kerneldemon was referring. I am pretty sure I know the places in this project, but I wasn't 100%, so I hedged. All in all, adhering to PSR-1 is good idea. I will get this repaired. I don't consider this an api-breaking change.

**Comment by kleetus** [comment]
only setting this in tests: 

./tests/Bitpay/Client/ClientTest.php:9:date_default_timezone_set('UTC');

**Comment by dopesong** [comment]
https://github.com/bitpay/php-bitpay-client/blob/4f370def472878b591afb686c69ed5cca223920d/src/Bitpay/Client/Client.php#L18 

LoL - nope 3.0.0 commit :)))))
