### ISSUE TITLE
Are you kidding me? Tag deleted?

### ISSUE THREAD

**Issue by dopesong** [bitpay/php-bitpay-client#198]
https://www.versioneye.com/php/bitpay:php-client/2.2.11

You deleted version? You understand that you ruined deployments because people use composer install instead of composer update to keep things stable?

Jesus guys - who told you that to do this is normal? @kleetus

**Comment by kleetus** [comment]
I referenced a need to do this a while back, 2.2.11 broke semantic versioning, this tag was deleted and moved to 3.x.

**Comment by dopesong** [comment]
You broke deployments dude. You deleted not one, but few.

Tags deleted: 
2.2.12 (Mar 04, 2016)
2.2.11 (Feb 16, 2016)
2.2.10 (Feb 05, 2016)
2.2.9 (Jan 25, 2016)

So you were able to create new one and fix it instead of deleting old ones.

When you make a BC and set wrong version - you make new tag with BC removed, but not deleting old versions.
