### ISSUE TITLE
[Bitpay Client] Get Rates using Request to live site

### ISSUE THREAD

**Issue by raul782** [bitpay/php-bitpay-client#201]
When calling the rates building the client and request on your own, I found 2 issues here in production site.

1- Given I want to know the USD rate, the sendRequest hits this endpoint: https://bitpay.com/rates/USD/ which makes the server redirect you to https://bitpay.com/rates/USD, if your CurlAdapter is not setup with this option: CURLOPT_FOLLOWLOCATION as true, then, the request fails.

2- When calling https://bitpay.com/rates/USD , the response is not correctly build, since the rate is cached, this method https://github.com/bitpay/php-bitpay-client/blob/master/src/Bitpay/Client/Response.php#L56 is not matching the headers correctly, therefore the body is returned with headers and content, making it hard to read the json content.

**Comment by kleetus** [comment]
on item 1:

> if your CurlAdapter is not setup with this option: CURLOPT_FOLLOWLOCATION as true, then, the request fails.

You can send in CURLOPT_FOLLOWLOCATION in the constructor to CurlAdapter. The internals of this class shouldn't assume the user wants to follow redirects.

on item 2:

Would you provide some sample code that exposes the issue? thanks!

**Comment by raul782** [comment]
@kleetus,
My mistake, found the issue, I was using www.bitpay.com and not bitpay.com as the host url.
