### ISSUE TITLE
Documentation not found

### ISSUE THREAD

**Issue by dopesong** [bitpay/php-bitpay-client#202]
Link in readme not exist: https://labs.bitpay.com/c/libraries/php

**Comment by TomaszKane** [comment]
I believe this issue should be reopen.

* http://php-bitpay-client.readthedocs.org/ ~ 404
* https://help.bitpay.com/8451-Implementation- ~ 404

**Comment by pieterpoorthuis** [comment]
Thanks, I've updated README.md
