### ISSUE TITLE
Symfony Config version

### ISSUE THREAD

**Issue by ienev** [bitpay/php-bitpay-client#209]
Is there any special reason to use 2.5.\* which is not maintained anymore? Plus this creates dependency hell when trying to install packages requiring newer versions of Symfony Config.

**Comment by GuidoHendriks** [comment]
Please fix this! 👍

**Comment by DeftNerd** [comment]
This is preventing me from using Bitpay right now. Please fix this.

**Comment by ienev** [comment]
I beleive #219 fixes this?

**Comment by pieterpoorthuis** [comment]
Fixed in the latest release (v2.2.12)
