### ISSUE TITLE
There is no way to get invoices

### ISSUE THREAD

**Issue by dopesong** [bitpay/php-bitpay-client#210]
Endpoint exists, method not.

Interface method commented out.

Any ETA when this will be implemented?

https://github.com/bitpay/php-bitpay-client/blob/da057b930fc8391894e596931e73bbd818d96aa6/src/Bitpay/Client/ClientInterface.php#L50

**Comment by pieterpoorthuis** [comment]
There is an endpoint to fetch an invoice:
`$invoice = $client->getInvoice($id);`
