### ISSUE TITLE
Requested package bitpay/php-client No version set (parsed as 1.0.0) is satisfiable by bitpay/php-client

### ISSUE THREAD

**Issue by kumaranoop83** [bitpay/php-bitpay-client#212]
Hi,

As soon as i add "php-client" in the requirement and try to update composer getting Problem 1 as follows.
------------composer.json------------
"require": {
        .....
        "bitpay/php-client": "^2.2"
    },

------------php composer.phar update bitpay/php-client------------
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bitpay/php-client No version set (parsed as 1.0.0) is satisfiable by bitpay/php-client[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Please help to fix this issue.

**Comment by TomaszKane** [comment]
Have similar problem: https://github.com/bitpay/php-bitpay-client/issues/221
