### ISSUE TITLE
Support for PHP 7

### ISSUE THREAD

**Issue by psampaz** [bitpay/php-bitpay-client#214]
Hi, 

are there any plans to support PHP 7 ?

thanks

**Comment by pieterpoorthuis** [comment]
Can you explain what is not working for you on PHP 7?
I've used the PHP library successfully on PHP 7

**Comment by psampaz** [comment]
Good to know that is works on php 7 :)

I just want to decide if I am going to use this library and I see that there is no explicit support for php 7 in composer.json or travis.yml

I am just asking if there will be an official support for php 7 from the bitpay team.

thanks

**Comment by psampaz** [comment]
Can you please let me know if there are plans for official support of php 7? I didn't understand why you just closed this issue.

thank you

**Comment by pieterpoorthuis** [comment]
We will update BitPay's PHP library if there are any issues with PHP 7 related issues. Since there are no known issues, I'm closing this issue.
