### ISSUE TITLE
Add Support for Zcash with your API

### ISSUE THREAD

**Issue by mineZcash** [bitpay/php-bitpay-client#218]
Hello, I am a Zcash user and we are looking for payment providers to help vendors start accepting Zcash. 

Have you considered adding Zcash to your accepted coins? Since you already deal with Bitcoin in your API it is not difficult to integrate Zcash since it is based on Bitcoin.

More detailed info here:   https://www.zcashcommunity.com/developers/

**Comment by pieterpoorthuis** [comment]
Thank you for the suggestion. Competition among cryptocurrencies is important, but we do not have plans to accept Zcash at this time.
