### ISSUE TITLE
Composer required?

### ISSUE THREAD

**Issue by TomaszKane** [bitpay/php-bitpay-client#221]
Please check this:

* uninstall php7.1-bcmath package
* add **"bitpay/php-client": "^2.2"** to composer.json
* run `composer update`

You probably got php-client in 2.2.0 version (old code that fail on generating private key).

After change composer to **"bitpay/php-client": "2.2.12"** and run `update` got error "Missing bcmath package" - what is ok.

Conclusions:
* bcmath is not installed by default
* by executing all the instructions in the readme, we don't get latest version of code

**Comment by pieterpoorthuis** [comment]
Yes... there is an issue with ^2.2 installing the the 2.2.0 version.. Also with a packagist not receiving the latest 2.2.12 version. I'm looking into that.

**Comment by TomaszKane** [comment]
Probably just missing `"ext-bcmath": "*"` here: https://github.com/bitpay/php-bitpay-client/blob/v2.2.0/composer.json#L32

**Comment by pieterpoorthuis** [comment]
I tried to reproduce, but installing bitpay/php-client ^2.2 installs the latest version (v2.2.13), including ext-bcmath

I'm not sure why the old php-client 2.2.0 is installed for some people that want to install the latest 2.2. If you know why this happens, I'm happy update the documentation.
