### ISSUE TITLE
Include refund

### ISSUE THREAD

**Issue by ajp8164** [bitpay/php-bitpay-client#224]

**Comment by dandelaney8** [comment]
seconded - is there really no way to issue a refund through this code? Been looking all over

**Comment by pieterpoorthuis** [comment]
there's no native function in the PHP library to issue refunds. But it's on the roadmap.

**Comment by TristanPie** [comment]
Any update on this ?

**Comment by anbugal** [comment]
@TristanPie we are currently working on a complete new SDK which most o the BitPay API resources and the last one of them (Refunds) will be available in the beginning of next week.

https://github.com/bitpay/php-bitpay-client-v2
