### ISSUE TITLE
IPN not work

### ISSUE THREAD

**Issue by shanmugakumar-s** [bitpay/php-bitpay-client#225]
I have configured IPN URL in coding and Bitpay payment tools page(payment tools->pont of sale->payment notification). but ipn does not work .I have a set URl in below coding. 

**$invoice
    ->setItem($item)
    ->setOrderId($order_id)
    ->setNotificationEmail($notificationmail)
    ->setRedirectUrl("http://emporium.osiztech.com/wallet/bitpay_return")
    ->setNotificationUrl("http://emporium.osiztech.com/wallet/bitpay_ipn);**

Please help what changed to do ?

**Sorry for poor English**

**Comment by pieterpoorthuis** [comment]
BitPay sends IPNs after an invoice receives a bitcoin transaction. Please check here for more information about blank IPNs: http://help.bitpay.com/businesses-and-organizations/implementation-and-development/why-am-i-getting-a-blank-ipn-post-response-from-bitpay-when-using-php

If this doesn't help, can you provide a BitPay invoice id that you paid? I can check the BitPay logs.

**Comment by leducson** [comment]
Hello.
Bitpay ipn response only https link, not support http link

**Comment by pieterpoorthuis** [comment]
BitPay advises to use https, but BitPay also supports sending IPNs to http URLs.

**Comment by msethi1980** [comment]
Hi,

I have set the IPN Url (https) and also set the flag "fullNotifications" to true but I don't get any control to the URL though the "redirectUrl" works.
The Invoice Id I have used is : 
https://test.bitpay.com/invoice?id=5Fmx3rsAesrDk2VsQic7Wf

Can you please help here.

Regards,
Manish

**Comment by pieterpoorthuis** [comment]
Answered in https://github.com/bitpay/php-bitpay-client/issues/248
