### ISSUE TITLE
Incorrect signature PHP 5.6.30-0+deb8u1)

### ISSUE THREAD

**Issue by juouy** [bitpay/php-bitpay-client#229]
Hello

I've been developing application using bitpay php api. 

I get the correct signature using windows platform and:
PHP 7.1.3 (cli) (built: Mar 14 2017 23:46:26) ( ZTS MSVC14 (Visual C++ 2015) x86 ) + gmp

I get error about wrong signature error from bitpay server on Debian 8 and:
PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21) + bcmath

I've been trying to debug the code you provided, this included using same private/public key pair for both servers. I've also disabled all random number generators to ensure same variables are used on both platforms. The troublemaking code is inside 

```
public function sign($data)` in PrivateKey.php
//make it static
 $k_hex = '0x5b3da3164c271422dca858fa952ebfc122cb6533f423f2ccf695afa6b487c146';
            $n_hex = '0x'.Secp256k1::N;



            $Gx = '0x'.substr(Secp256k1::G, 2, 64);
            $Gy = '0x'.substr(Secp256k1::G, 66, 64);

            var_dump($Gx);
            var_dump($Gy);
//All is fine here, same result on both platforms

            $P = new Point($Gx, $Gy);

            // Calculate a new curve point from Q=k*G (x1,y1)
            $R = Util::doubleAndAdd($k_hex, $P);
var_dump($R);
//Total failure, $R is different on both platforms
```
**Windows platform php 7.1 gmp**

> string(66) "0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798"
> string(66) "0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8"
> 
> class Bitpay\Point#715 (2) {
>   protected $x =>
>   string(77) "50453129686613788604125161042609028849818371448464351125032383673052356068371"
>   protected $y =>
>   string(77) "88553014160811025886569019435874510614330907789532938873693208502562925959999"
> }

**Windows platform php 5.6.30 gmp**

> string(66) "0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798"
> string(66) "0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8"
> object(Bitpay\Point)#715 (2) {
>   ["x":protected]=>
>   string(77) "50453129686613788604125161042609028849818371448464351125032383673052356068371"
>   ["y":protected]=>
>   string(77) "88553014160811025886569019435874510614330907789532938873693208502562925959999"
> }
> 

**Debian 8 php 5.6.30 bcmath**

> string(66) "0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798"
> string(66) "0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8"
> object(Bitpay\Point)#717 (2) {
>   ["x":protected]=>
>   string(76) "1655131353631170967831041993909351382093976689891354157363868361160200935921"
>   ["y":protected]=>
>   string(77) "59690876060178921410912740954616764085578618136340268137145027661787185985212"
> }
> 
> 

Any idea what might be wrong?

//Edit

**Windows server is using gmp as math engine but Debian is using bcmath.** Can this cause the problem?

//Edit 2

Yes, after switching math engine to gmp all is fine. So it seems using bcmath is producing wrong signature and bitpay server won't accept it. Try it yourself.

**Comment by kleetus** [comment]
it could be related to this:

https://github.com/bitpay/php-bitpay-client/blob/cd6b0860ac34d03e552ee28fc703ac7adb43c021/src/Bitpay/Util/Util.php#L225

Both call decToBin, which makes calls into Math:: either in bcmath or gmp. I am curious if the return values are the same for bcmath and gmp? I am guessing this is where the problems lies if I had to make a wild guess from the outset.

If I had to take an even further wild guess, I would bet the behavior of Math::div is not the same between bcmath and gmp. Possibly a rounding issue, I am not sure. You stated that bcmath, ultimately, produced and incorrect signature, at least with php 5.6.30-0+deb8u1. I can take a look at that.

**Comment by juouy** [comment]
Yes, i think it's kinda critical issue. In such scenario you should require users to use gmp.
I didn't use any fancy configuration, just basic debian 8 with php. So it affects many users.

I didn't dig in more, when i found out that switching math engine solves issue.

**Comment by quantumwebco** [comment]
I have the same error on an MS Azure app server with PHP-5.6.30 on Windows NT RD0003FFA23CC4 6.2 build 9200 (Windows Server 2012 Datacenter Edition) i586

Definitely looks like a critical issue with php 5.6.3 and bcmath.

How to switch math engine?

**Comment by ajp8164** [comment]
> How to switch math engine?

The PHP library prefers gmp over bcmath.  To use gmp you must have installed and properly configured for php and apache.

**Comment by quantumwebco** [comment]
I ended up editing the core files to output proper errors as it just gives generic messages which is no help whatsoever. 

Still haven't got any reasonable answers as to how to make this work. 

If it's not possible to have GMP on a server and bcmath has a critical issue then basically this library doesn't work. 

How to install and enable GMP on a windows server?? Or how to make bcmath work??

Can anyone recommend another bitcoin api that does actually work? 

Thanks

**Comment by pieterpoorthuis** [comment]
I'm trying to replicate the issue, but gmp & bcmath are returning the same values for me. I've used the values you put in your example to calculate R, using gmp & bcmath:
```
MacBook-Air$ /usr/local/opt/php71/bin/php create_invoice.php 
Using engine BCMATH...
entering PrivateKey -> Sign
Math Engine is: BCMATH
string(66) "0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798"
string(66) "0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8"
object(Bitpay\Point)#19 (2) {
  ["x":protected]=>
  string(77) "50453129686613788604125161042609028849818371448464351125032383673052356068371"
  ["y":protected]=>
  string(77) "88553014160811025886569019435874510614330907789532938873693208502562925959999"
}
Invoice "..." created, see https://test.bitpay.com/invoice?id=....

MacBook-Air$ php56 create_invoice.php 
Using engine GMP...
entering PrivateKey -> Sign
Math Engine is: GMP
string(66) "0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798"
string(66) "0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8"
object(Bitpay\Point)#19 (2) {
  ["x":protected]=>
  string(77) "50453129686613788604125161042609028849818371448464351125032383673052356068371"
  ["y":protected]=>
  string(77) "88553014160811025886569019435874510614330907789532938873693208502562925959999"
}
Invoice "..." created, see https://test.bitpay.com/invoice?id=...
```

Question: can you show your bcmath configuration, e.g. using:
```
MacBook-Air$ php --ri bcmath
bcmath
BCMath support => enabled
Directive => Local Value => Master Value
bcmath.scale => 0 => 0
```

**Comment by quantumwebco** [comment]
Because this is an issue on WINDOWS. You are testing on a mac.

**Comment by pieterpoorthuis** [comment]
I tried on Windows, Ubuntu, Mac OS and Debian 8 and it works just fine for me: invoices are created while using bcmath as the engine. So I still can't reproduce... 

If @juouy or @quantumwebco would like to help me reproduce the issue, would be great. If you want we can do screensharing via Skype. Drop me a line at integrations@bitpay.com
