### ISSUE TITLE
reconciliation error

### ISSUE THREAD

**Issue by pravithapk** [bitpay/php-bitpay-client#230]
while trying to fetch reconciliation report getting error like "This endpoint does not support the `merchant` facade". 
reconciliation is for merchant facade itself.

**Comment by pieterpoorthuis** [comment]
Fetching a settlement report (https://bitpay.com/api#resource-Settlements) is a 2 step approach:

1) Please use the merchant facade to fetch the settlement report summary for a date range.
2) The response will contain a resource token. Please use the resource token to fetch the settlement report details.
