### ISSUE TITLE
Merchant Token

### ISSUE THREAD

**Issue by quantumwebco** [bitpay/php-bitpay-client#231]
Hi there

I have managed to get a response to create a merchant token by using curl instead of the library as it just doesn’t seem to work as expected. $getToken = $client->createToken($tokenOptions); does not return a pairing code if the façade is set to merchant. When I curl the same token options post fields I get the expected JSON response.

$token = $client->createToken(
 array(
 'facade' => 'merchant',
 'label' => 'You can insert a label here',
 'id' => (string) $sin,
 )
 );

The response I get from this if I var_dump($token) is…

object(Bitpay\Token)[12]
  protected 'token' => string '9hR4TLG4pNrKfcNisKQCaPUGQaoJfGk751WobWDzaYXk' (length=44)
  protected 'resource' => null
  protected 'facade' => string 'merchant' (length=8)
  protected 'createdAt' => float 1496416119267
  protected 'policies' => 
    array (size=1)
      0 => 
        array (size=3)
          'policy' => string 'id' (length=2)
          'method' => string 'inactive' (length=8)
          'params' => 
            array (size=1)
              ...

Bitpay\Token Object
(
    [token:protected] => 6ZTCn8eGSUxkN2DKj6gQWwJomBDWs3iAdpuwTZCvxsSe
    [resource:protected] => 
    [facade:protected] => merchant
    [createdAt:protected] => 1496416184057
    [policies:protected] => Array
        (
            [0] => Array
                (
                    [policy] => id
                    [method] => inactive
                    [params] => Array
                        (
                            [0] => TfGxA6bAyLC57CWEJ8U4dZc1SZinuqSRrEW
                        )

                )

        )

)

Where is the pairing code please??

**Comment by pieterpoorthuis** [comment]
Hi,

The pairing code will be in the client response, as in:
 $response = $client->getResponse();
 echo (string) $response.PHP_EOL.PHP_EOL;

**Comment by quantumwebco** [comment]
It is not. I have posted the response received. There is no pairing code.

**Comment by pieterpoorthuis** [comment]
You posted the $token contents, but the pairing code will be in the $client->getResponse().
