### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by quantumwebco** [bitpay/php-bitpay-client#232]
How to set notificationURL for the invoice??

**Comment by pieterpoorthuis** [comment]
The tutorial provides an example for setting the notificationURL:
https://github.com/bitpay/php-bitpay-client/blob/master/examples/tutorial/003_createInvoice.php#L76

**Comment by quantumwebco** [comment]
Not for a subscription.

**Comment by pieterpoorthuis** [comment]
It's currently not possible to the notificationURL for a bill or subscription
