### ISSUE TITLE
Cannot generate temp/bitpay.pr

### ISSUE THREAD

**Issue by Maerryham** [bitpay/php-bitpay-client#239]
Please i need urgent help, I tried to run 001.php tutorial which is supposed to generate my private key and public key, but i think my windows is not giving write permissions for the file, please help me out

![capture](https://user-images.githubusercontent.com/19529477/27381919-9053874c-567c-11e7-9e28-87223d83eb4b.PNG)

**Comment by pieterpoorthuis** [comment]
You can easily fix this by either changing the path of the keys to a place that has write access.
