### ISSUE TITLE
No callback for Invoice with status "new"

### ISSUE THREAD

**Issue by MoritzVonWirth** [bitpay/php-bitpay-client#244]
When I use this code:
```
$invoice->setNotificationUrl($uri);
$invoice->setFullNotifications(true);
```
I dont get a callback with the status "new".
It doesnt work anymore since 2 weeks.
All callbacks that I recieve are status: "paid", "confirmed" and "complete".

**Comment by pieterpoorthuis** [comment]
IPN 'new' should be sent for paidPartial payments. Can you provide a BitPay invoice id where you expected status 'new'?

**Comment by MoritzVonWirth** [comment]
It was my mistake, I've misunderstood it in the documentation.
I didtn know that 'new' should only be sent for paidPartial.

Thanks for your fast response, I'm really sorry.
