### ISSUE TITLE
Unable to create token

### ISSUE THREAD

**Issue by Nobitasean** [bitpay/php-bitpay-client#245]
Client.php line:505

**Comment by Nobitasean** [comment]
$client->createToken respond error: Unable to create token

**Comment by pieterpoorthuis** [comment]
Please make sure you use a valid pairingCode, created with a valid BitPay merchant account on www.bitpay.com.

The code examples from the tutorial show to catch the exception and print more info:
https://github.com/bitpay/php-bitpay-client/blob/master/examples/tutorial/002_pair.php
