### ISSUE TITLE
Extended Notifications not working

### ISSUE THREAD

**Issue by dandelaney8** [bitpay/php-bitpay-client#246]
IPN calls to my server are working fine - getting paid, confirmed, and complete notifications correctly. However, when I run this:

`$invoice->setExtendedNotifications(true);`

Before creating my invoice, I don't get any IPN calls. What's going on here?

**Comment by pieterpoorthuis** [comment]
Can you provide some invoice ids where you have extendedNotifications=true, and you expected IPNs that were not delivered?

**Comment by dandelaney8** [comment]
sure, these two:

GHyD39MKcsSXCQAfJksnvn
4SRsdKR3m2jS18yzJgsECu

**Comment by pieterpoorthuis** [comment]
paid&confirmed&complete webhooks were sent, but your server responded with HTTP 500.

**Comment by dandelaney8** [comment]
hmmmm, is there something different about these that might cause this?
Everything works fine when extendedNotifications is false.

**Comment by pieterpoorthuis** [comment]
Yes, the following is added when using extendedNotifications:
* an event block is added to the beginning (containing code + name, indicating the type of event)
* the payload is put in a data block
Example:
{ event: { code: 1006, name: 'invoice_completed' },
       data: 
        { id: 'GHyD39MKcsSXCQAfJksnvn',
          url: 'https://test.bitpay.com/invoice?id=GHyD39MKcsSXCQAfJksnvn',
          posData: '',
          status: 'complete',
          btcPrice: '0.005797',
          price: 25,
          currency: 'USD',
          invoiceTime: 1503934496168,
          expirationTime: 1503935396168,
          currentTime: 1503939679299,
          btcPaid: '0.005797',
          btcDue: '0.000000',
          rate: 4312.3,
          exceptionStatus: false,
          buyerFields: 
           { buyerName: '',
             buyerAddress1: '',
             buyerAddress2: '',
             buyerCity: null,
             buyerState: null,
             buyerZip: null,
             buyerCountry: null,
             buyerEmail: 'test@test.com',
             buyerPhone: null,
             buyerNotify: null } } }

**Comment by dandelaney8** [comment]
ahhh I see. So the first few lines of my IPN endpoint are as follows

`$data = file_get_contents("php://input");
        if ($data && ($ipn = json_decode($data))) {
            if ($id = $ipn->id) {`

This is likely causing the 500 error when I try to grab the "id", yes? How would you suggest parsing the new data format? I'm confused about what you mean by "the payload is put in a data block"

**Comment by dandelaney8** [comment]
got it thanks!
