### ISSUE TITLE
help with installing and required dependencies

### ISSUE THREAD

**Issue by avieru** [bitpay/php-bitpay-client#251]
I'm having trouble installing this via composer, wondering what to do here. Does the screenshot help? Thank you

![image](https://user-images.githubusercontent.com/225759/31641410-6157a97c-b2b2-11e7-9670-851253ad276c.png)

**Comment by pieterpoorthuis** [comment]
Can you show the commands you used?
Did you follow the instructions from https://github.com/bitpay/php-bitpay-client/blob/master/README.md ?

**Comment by avieru** [comment]
@pieterpoorthuis yes, of course. Tried both ways.  "Via composer by hand" and "install using composer".

Same result unfortunately. Below is my "require" from composer.json, for reference.

`  "require": {
    "php": ">=5.5.9",
    "laravel/framework": "5.2.*",
    "barryvdh/laravel-ide-helper": "2.2.*",
    "invisnik/laravel-steam-auth": "2.3.*",
    "invisnik/laravel-steam-inventory": "dev-master",
    "predis/predis": "1.1.*",
    "tymon/jwt-auth": "1.0.0-beta.1",
    "anlutro/curl": "1.4.*",
    "doctrine/dbal": "2.*",
    "sunra/php-simple-html-dom-parser": "1.5.2",
    "maxmind/minfraud": "^1.3",
    "paypal/rest-api-sdk-php": "^1.11",
    "guzzlehttp/guzzle": "^6.2",
    "watson/rememberable": "2.0.*",
    "geoip2/geoip2": "2.4.*",
    "torann/geoip": "1.0.*",
    "phpoffice/phpexcel": "1.8.*",
    "rap2hpoutre/laravel-log-viewer": "^0.10.4",
    "aws/aws-sdk-php": "~3.0",
    "thatsus/laravel-redlock": "^3.0"
  },`

**Comment by sbacelic** [comment]
could you paste the output of **composer depends symfony/event-dispatcher**

**Comment by pieterpoorthuis** [comment]
It seems you're trying to install an outdated BitPay PHP library v2.2.0

Can you try the following:
php composer.phar require bitpay/php-client:~2.2

If the above doesn't work, can you try:
php composer.phar require bitpay/php-client:2.2.15
