### ISSUE TITLE
Error :This endpoint does not support the `user` facade

### ISSUE THREAD

**Issue by Klarwasser** [bitpay/php-bitpay-client#253]
By creating a Invoice i become this Error.
Token ,Key and Sin are correct.
Can anyone help me please?
`11-20 22:09:56: Bitpay\Client\Response Object
(
    [raw:protected] => HTTP/1.1 200 OK
Date: Mon, 20 Nov 2017 21:09:55 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 279
Connection: keep-alive
Set-Cookie: __cfduid=d2116c6677c67a2b5881b49d537ccfeb31511212195; expires=Tue, 20-Nov-18 21:09:55 GMT; path=/; domain=.bitpay.com; HttpOnly
Strict-Transport-Security: max-age=31536000
X-Download-Options: noopen
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: HEAD,GET,POST,PUT,DELETE,OPTIONS
Access-Control-Allow-Headers: Content-Type,Authorization,Content-Length,X-Requested-With,Cache-Control,X-Accept-Version,x-signature,x-pubkey,x-identity,cf-connecting-ip
ETag: W/"117-DwMzKwkGMJWjPVsJFOJy6dG+Eck"
set-cookie: connect.sid=s%3ApdC1pnpraR9oB5wIzLOVqClDb9dTQAXW.jSywZsiPnKlhb1f7ZO%2BMzs0BhX%2F23rGNVVDsFknLFUM; Path=/; HttpOnly; Secure
Server: cloudflare-nginx
CF-RAY: 3c0e649cca45134d-LHR

{"data":[{"policies":[{"policy":"id","method":"require","params":["Tf2Gzfst1o7p6cZXaCGUNFzSpqGQHgkXRWJ"]}],"resource":"AtsQGS1TZzbQskp7L8GWGkmGwfte8qT6yWseCtmLiciB","token":"ArmcoLsi3qZoj86sFd4mz9","facade":"pos","label":"Modulexpert Bitpay Plugin","dateCreated":1511211874485}]}
    [headers:protected] => Array
        (
            [Date] =>  Mon, 20 Nov 2017 21
            [Content-Type] =>  application/json; charset=utf-8
            [Content-Length] =>  279
            [Connection] =>  keep-alive
            [Set-Cookie] =>  __cfduid=d2116c6677c67a2b5881b49d537ccfeb31511212195; expires=Tue, 20-Nov-18 21
            [Strict-Transport-Security] =>  max-age=31536000
            [X-Download-Options] =>  noopen
            [X-Content-Type-Options] =>  nosniff
            [Access-Control-Allow-Origin] =>  *
            [Access-Control-Allow-Methods] =>  HEAD,GET,POST,PUT,DELETE,OPTIONS
            [Access-Control-Allow-Headers] =>  Content-Type,Authorization,Content-Length,X-Requested-With,Cache-Control,X-Accept-Version,x-signature,x-pubkey,x-identity,cf-connecting-ip
            [ETag] =>  W/"117-DwMzKwkGMJWjPVsJFOJy6dG+Eck"
            [set-cookie] =>  connect.sid=s%3ApdC1pnpraR9oB5wIzLOVqClDb9dTQAXW.jSywZsiPnKlhb1f7ZO%2BMzs0BhX%2F23rGNVVDsFknLFUM; Path=/; HttpOnly; Secure
            [Server] =>  cloudflare-nginx
            [CF-RAY] =>  3c0e649cca45134d-LHR
        )

    [body:protected] => {"data":[{"policies":[{"policy":"id","method":"require","params":["Tf2Gzfst1o7p6cZXaCGUNFzSpqGQHgkXRWJ"]}],"resource":"AtsQGS1TZzbQskp7L8GWGkmGwfte8qT6yWseCtmLiciB","token":"ArmcoLsi3qZoj86sFd4mz9","facade":"pos","label":"Modulexpert Bitpay Plugin","dateCreated":1511211874485}]}
    [statusCode:protected] => 200
)

11-20 22:09:56: Invoice gesetzt 
11-20 22:09:56: Bitpay Kunde gesetzt 
11-20 22:09:57: Error im Abschnitt ErstelleBitpay(CreateInvoice)
11-20 22:09:57: Request :POST https://test.bitpay.com:443/invoices HTTP/1.1
Content-Type: application/json
X-BitPay-Plugin-Info: BitPay PHP-Client/0.0.0
User-Agent: BitPay PHP-Client/0.0.0 (PHP 5.6.30)
X-Accept-Version: 2.0.0
x-identity: 02889e4b476a49024998143973107e50372b762dfc5fe39aabb8a4640c51c663f6
x-signature: 3044022009086589d7f068b4079b81f87e0dd5b3bda6102014975d5ddb60570cd6606fda0220082143156d202fd4a8ce1334335f52376e7181754c7d711b33b0e57b20768884
11-20 22:09:57: Response :HTTP/1.1 401 Unauthorized
Date: Mon, 20 Nov 2017 21:09:57 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 60
Connection: keep-alive
Set-Cookie: __cfduid=d70da7857d3231370ab1c70ddf1c7bcb61511212196; expires=Tue, 20-Nov-18 21:09:56 GMT; path=/; domain=.bitpay.com; HttpOnly
Strict-Transport-Security: max-age=31536000
X-Download-Options: noopen
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: HEAD,GET,POST,PUT,DELETE,OPTIONS
Access-Control-Allow-Headers: Content-Type,Authorization,Content-Length,X-Requested-With,Cache-Control,X-Accept-Version,x-signature,x-pubkey,x-identity,cf-connecting-ip
ETag: W/"3c-yVv/7rJRfF6QLK8eJWWlLJx/NBI"
set-cookie: connect.sid=s%3A_WZCEizI1pG5z4hrx36lquVsz-WgkrvH.iR0H%2BubdhtWpHaQL1qcOizEsG0PWb%2BS1M%2BMlk9H%2Ftck; Path=/; HttpOnly; Secure
Server: cloudflare-nginx
CF-RAY: 3c0e64a5a8e83506-LHR

{"error":"This endpoint does not support the `user` facade"}`

**Comment by pieterpoorthuis** [comment]
From the error it looks like you're passing a token that is not linked to the POS or Merchant facade.

Did you try to use the 4 examples from the tutorial:
https://github.com/bitpay/php-bitpay-client/tree/master/examples/tutorial

**Comment by Klarwasser** [comment]
Hello!
The Plugin runs in over 50 Shops but in only 6 Shops i have this Problem
i use a pairingcode

**Comment by pieterpoorthuis** [comment]
can you email me at pieter at bitpay com ? I expect to need more info & interaction to resolve this.
