### ISSUE TITLE
McryptExtension wrapper still in use?

### ISSUE THREAD

**Issue by sbacelic** [bitpay/php-bitpay-client#254]
Do you have plans to abandon this extension? It seems like it's not used anymore or at least I couldn't find the use case for McryptExtension wrapper in the documentation/examples.

As _ext-mcrypt_ is abandoned in PHP 7.1 and will be removed in PHP 7.2 (though still in PECL) it might be good to consider removing the dependency on this extension/class. If necessary McryptExtension could be moved to external package and suggested in composer.json for those who would still like to use _ext-mcrypt_.

**Comment by pieterpoorthuis** [comment]
fixed in v2.2.15
