### ISSUE TITLE
Wrong invoice dates parsing

### ISSUE THREAD

**Issue by SilverFire** [bitpay/php-bitpay-client#257]
Currently `https://bitpay.com/invoices/%invoiceId%` returns time with milliseconds as follows:

```php
    'invoiceTime' => '1512559263104',
    'expirationTime' => '1512560163104',
    'currentTime' => '1512562237964',
```

Time assignation in `Invoice.php` on [:477](https://github.com/bitpay/php-bitpay-client/blob/7a06724b25e1205dc4e7dae19d6b49a183e6f62c/src/Bitpay/Invoice.php#L477), [:502](https://github.com/bitpay/php-bitpay-client/blob/7a06724b25e1205dc4e7dae19d6b49a183e6f62c/src/Bitpay/Invoice.php#L502), [:527](https://github.com/bitpay/php-bitpay-client/blob/7a06724b25e1205dc4e7dae19d6b49a183e6f62c/src/Bitpay/Invoice.php#L527) is performed with assumption that timestamp is in seconds, that leads to obviously wrong DateTime object with date in far far future: `49901-02-15T09:51:44+01:00`

See: https://3v4l.org/DUlIi

**Comment by pieterpoorthuis** [comment]
Fixed in v2.2.16
