### ISSUE TITLE
Not receiving IPNs

### ISSUE THREAD

**Issue by Martok88** [bitpay/php-bitpay-client#258]
I've set up my script using the testnet, but I'm not receiving any IPNs from bitpay. Manually sending an IPN with curl works as expected.

**Comment by pieterpoorthuis** [comment]
We have some issues with IPNs on test.bitpay.com not working since yesterday. We'll get it fixed today.

**Comment by hopeseekr** [comment]
I'm having this exact same problem on testnet this entire week of late February...

**Comment by pieterpoorthuis** [comment]
Can you provide an example BitPay invoice id?

**Comment by hopeseekr** [comment]
I found out that it just doesn't work on TestNet. works all the time on LIvenet.

**Comment by pieterpoorthuis** [comment]
Can you provide an example BitPay invoice id for which you expected an IPN?
