### ISSUE TITLE
BitPay API Changes for BCH payments

### ISSUE THREAD

**Issue by fwermelinger** [bitpay/php-bitpay-client#260]
I got an email notification that Bitpay is going to support BCH payments this week. Our company wants to start using it as soon as possible but we'll have to make some changes to this client to get all the information about how much of what was paid in an invoice. From the email I get that the only changes are mostly fields added to the InvoiceInterface.php:

- transactionCurrency
- amountPaid
- exchangeRates
- paymentSubtotals
- paymentTotals

Is someone already working on making these changes to the client?

**Comment by pieterpoorthuis** [comment]
Yes. We just released v2.2.19 with the BCH changes
