### ISSUE TITLE
Version 3.x doesn't support for the new, BCH-enabled API (yet)

### ISSUE THREAD

**Issue by petski** [bitpay/php-bitpay-client#263]
i.e. no way to set `supportedTransactionCurrencies` for an invoice https://bitpay.com/api#resource-Invoices

**Comment by pieterpoorthuis** [comment]
as soon as supportedTransactionCurrencies will be fully supported by BitPay's API, I will put it in the PHP library. For now it's not possible to create BTC only invoices.

**Comment by petski** [comment]
Ok, thanks, will this also be for the 3.x version(s)?

**Comment by pieterpoorthuis** [comment]
No, the 3.x version is not maintained.

All development goes in the 2.x version
