### ISSUE TITLE
Error at confirm: We were unable to decode your transaction

### ISSUE THREAD

**Issue by StingNguyen** [bitpay/php-bitpay-client#270]
I have get a Error:

https://test.bitpay.com/invoice?id=YMXhsmRwtbLUNzGKQoheFd

![9f720971-57a8-4685-8417-708bd6c3d85c](https://user-images.githubusercontent.com/1131069/38203461-7e5b58c0-36c9-11e8-8d7c-878dd8bdbab9.jpg)

**Comment by StingNguyen** [comment]
$item = new \Bitpay\Item();
        $item->setPrice($params['price']);
        $item->setDescription($params['description']);
        $invoice->setRedirectUrl($params['redirect']);
        $invoice->setItem($item);

**Comment by StingNguyen** [comment]
could you help me?

**Comment by pieterpoorthuis** [comment]
The error was on BitPay's side and has been fixed. 

You should now be able to pay test BTC invoices on test.bitpay.com
