### ISSUE TITLE
Problem by install php-client

### ISSUE THREAD

**Issue by Klarwasser** [bitpay/php-bitpay-client#272]
Hello
Then i use : php composer.phar require bitpay/php-client:~4.0
it come follow text. How do i Fix that ? Can me one help please.

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bitpay/php-client ~4.0 is satisfiable by bitpay/php-client[4.0.x-dev] but these conflict with your requirements or minimum-stability.

**Comment by pieterpoorthuis** [comment]
Sorry. The v4 client will be released next week. I've updated the readme doc.

Currently, the 2.2 client is the latest stable version.
