### ISSUE TITLE
Obscure error message from the bitpay server

### ISSUE THREAD

**Issue by Dadibom** [bitpay/php-bitpay-client#273]
```
Exception: Could not load token access in file /var/www/laravel/vendor/bitpay/php-client/src/Bitpay/Client/Client.php on line 174
Stack trace:
  1. Exception-&gt;() /var/www/laravel/vendor/bitpay/php-client/src/Bitpay/Client/Client.php:174
  2. Bitpay\Client\Client-&gt;createInvoice() 
```

Worked a couple of months ago, haven't changed anything since. It simply does not work anymore. Tried updating from 2.x.x to 3.x.x but i'm still getting the same error. The message does not exist in the code, nor on google, so i really got no idea what's wrong.

Using testnet on a merchant facade

**Comment by pieterpoorthuis** [comment]
Are you using a laravel wrapper? From the output it looks like the wrapper is looking for a BitPay token, but can't find it.

**Comment by Dadibom** [comment]
Hi Pieter, this was due to the testnet accounts being removed/reset, so I had to open a new one. Forgot to close the issue :)

Although the error message could have been clearer!
