### ISSUE TITLE
php version requirements

### ISSUE THREAD

**Issue by itelmenko** [bitpay/php-bitpay-client#276]
Your library require php 5.4. But it works fine 5.3.10  for me.
I have created fork where I changed php version in composer.json. It works fine.
But it is very uncomfortable to use a fork. Can you change requirements to php 5.3 ?

**Comment by peter279k** [comment]
Actually, the `php-5.3` version is too old.

I think the package requires `php-5.4` at least is looks good :).

**Comment by itelmenko** [comment]
It is not actual issue for me now

**Comment by peter279k** [comment]
@itelmenko, thank you for your reply.

It's not an actual issue now, and I think this issue should be closed :-).
