### ISSUE TITLE
when i call getting below error examples/tutorial/002_pair.php

### ISSUE THREAD

**Issue by quamer123** [bitpay/php-bitpay-client#301]
Notice: Undefined variable: facade in C:\xampp\htdocs\bit_pay2\php_bitpay2\examples\tutorial\002_pair.php on line 78

Notice: Undefined offset: 2 in C:\xampp\htdocs\bit_pay2\php_bitpay2\src\Bitpay\Client\Response.php on line 76
Exception occured: 0: Unable to create token Pairing failed. Please check whether you're trying to pair a production pairing code on test. POST https://test.bitpay.com:443/tokens HTTP/1.1 Content-Type: application/json X-BitPay-Plugin-Info: BitPay PHP-Client/4.0.0 User-Agent: BitPay PHP-Client/4.0.0 (PHP 7.1.27) X-Accept-Version: 2.0.0 Content-Length: 137 {"pairingCode":"StCSF6w","label":"manage token","id":"Tf1j5yp3t5hDgJuWqHatwYqztNjsVactH7a","guid":"27b767c7-cb95-48b4-747b-8cbe67c3a5b2"} HTTP/2 500 date: Sat, 10 Aug 2019 05:18:34 GMT content-type: application/json; charset=utf-8 content-length: 34 set-cookie: __cfduid=daaf1a2cf3d4bd9faba77cb0661c4d88d1565414313; expires=Sun, 09-Aug-20 05:18:33 GMT; path=/; domain=.bitpay.com; HttpOnly strict-transport-security: max-age=31536000 x-download-options: noopen x-content-type-options: nosniff access-control-allow-origin: * access-control-allow-methods: HEAD,GET,POST,PUT,DELETE,OPTIONS access-control-allow-headers: Content-Type,Authorization,Content-Length,X-Requested-With,Cache-Control,X-Accept-Version,x-signature,x-pubkey,x-identity,x-bitpay-version,cf-connecting-ip etag: W/"22-YY3KKJxeBwOwdrcW/OQxYqSp3GY" set-cookie: connect.sid=s%3ANKM0tWQkgKwD7Uu4JrqH7JCXLYJYdJ3f.dbyN9OIsSsl3Sr24gBMBP4eu5KOmfgf08V%2BGd6oLcno; Path=/; HttpOnly; Secure expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct" server: cloudflare cf-ray: 503f8280beda8aa1-BOM {"error":"Unable to create token"}

**Comment by thejoshualewis** [comment]
Responded in Zendesk ticket
