### ISSUE TITLE
Unsuccessful HTTP response for sequential request for testnet

### ISSUE THREAD

**Issue by nikhilbangre** [bitpay/php-bitpay-client#305]
first payment gets successful but if we start the next payment it gets **Unsuccessful HTTP response** error. but after some time (maybe in 5 min) payment get successful.

**Comment by anbugal** [comment]
Hi @nikhilbangre, this repository is no longer maintained, please, move to the new library, which is fully updated and faster to integrate: https://github.com/bitpay/php-bitpay-client-v2
